version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-desafio}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 10s
      retries: 30
    restart: unless-stopped

  backend:
    build:
      context: ./desafioTecnico
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://db:3306/desafio?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-root}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://frontend}
      JWT_SECRET: ${JWT_SECRET:-c3V4LXNoYS1zZWNyZXRhLTI1Ni1iYXNlNjQ=}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-3600000}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./biblioteca-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-http://backend:8080/api/v1}
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80" 
    restart: unless-stopped

volumes:
  db-data:
